import "~/styles/globals.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function Navbar(){
  return (
    <div className="flex justify-between text-xl py-2 px-4 bg-slate-900">
      <h1>Gallery</h1>
      <h1>Sign In</h1>
    </div>

  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        < Navbar />
        {children}
      </body>
    </html>
  );
}
